const users = [
    //we just need to add url of profile pics , i add user profile pics for the function to show user image or there new uploaded image if they decide to change
    {
      //check file path just added them
      name: "John Smith",
      username: "johnsmith",
      email: "john@email.com",
      password: "password",
      phone: "555-555-5555",
      bio: "I am a full stack developer with 5 years of experience.",
      salaryExpectation: "$100,000 - $120,000 yearly",
      profilePictureUrl: "./client/src/assets/images/pre-profile-pic1.jpg",
      listings: [],
      savedListings: [],
    },
    {
      name: "Alice Johnson",
      username: "alicejohnson",
      email: "alice@email.com",
      password: "securepass",
      phone: "555-123-4567",
      bio: "I am a registered nurse with 10 years of experience.",
      salaryExpectation: "$70,000 - $90,000 yearly",
      profilePictureUrl: "/client/src/assets/images/pre-profile-pic1.jpg",
      listings: [],
      savedListings: [],
    },
    {
      name: "Robert Davis",
      username: "robertdavis",
      email: "robert@email.com",
      password: "pass123",
      phone: "555-789-0123",
      bio: "I am a data scientist with 3 years of experience.",
      salaryExpectation: "$120,000 - $140,000 yearly",
      profilePictureUrl: "./client/src/assets/images/Screenshot(384).png",
      listings: [],
      savedListings: [],
    },
    {
      name: "Emily White",
      username: "emilywhite",
      email: "emily@email.com",
      password: "mypassword",
      phone: "555-456-7890",
      bio: "I am a graphic designer with 5 years of experience.",
      salaryExpectation: "$55,000 - $70,000 yearly",
      profilePictureUrl: "./client/src/assets/images/about-yesenia.png",
      listings: [],
      savedListings: [],
    },
    {
      name: "Daniel Brown",
      username: "danielbrown",
      email: "daniel@email.com",
      password: "danny123",
      phone: "555-987-6543",
      bio: "I am a construction project manager with 8 years of experience.",
      salaryExpectation: "$90,000 - $110,000 yearly",
      profilePictureUrl: "./client/src/assets/images/about-joseph.jpg",
      listings: [],
      savedListings: [],
    },
    {
      name: "Elena Martinez",
      username: "elenamartinez",
      email: "elena@email.com",
      password: "elena123",
      phone: "555-111-2222",
      bio: "I am a marketing coordinator with 2 years of experience.",
      salaryExpectation: "$50,000 - $60,000 yearly",
      profilePictureUrl: "./client/src/assets/images/portfolio.jpeg",
      listings: [],
      savedListings: [],
    },
    {
      name: "Samuel Turner",
      username: "samuelturner",
      email: "sam@email.com",
      password: "sammy456",
      phone: "555-333-4444",
      bio: "I am a customer support specialist with 1 year of experience.",
      salaryExpectation: "$40,000 - $50,000 yearly",
      profilePictureUrl: "./client/src/assets/images/about-Nathaniel.jpg",
      listings: [],
      savedListings: [],
    },
    {
      name: "Megan Williams",
      username: "meganwilliams",
      email: "megan@email.com",
      password: "meganpass",
      phone: "555-555-6666",
      bio: "I am a retail sales associate with 2 years of experience.",
      salaryExpectation: "$30,000 - $40,000 yearly",
      profilePictureUrl: "./client/src/assets/images/about-katie.jpg",
      listings: [],
      savedListings: [],
    },
    {
      name: "David Miller",
      username: "davidmiller",
      email: "david@email.com",
      password: "davidpass123",
      phone: "555-777-8888",
      bio: "I am an electrical engineer with 4 years of experience.",
      salaryExpectation: "$80,000 - $100,000 yearly",
      profilePictureUrl: "./client/src/assets/images/Screenshot(384).png",
      listings: [],
      savedListings: [],
    },
    {
      name: "test",
      username: "test",
      email: "test@email.com",
      password: "asdf",
      phone: "555-555-5555",
      bio: "test",
      salaryExpectation: "test",
      profilePictureUrl: "./client/src/assets/images/pre-profile-pic1.jpg",
      listings: [],
      savedListings: [],
    }
  ];

  module.exports = users;